name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # 4. (Optional) Run frontend tests
      # Disabled to prevent ESM/Jest errors in CI
      # - name: Run frontend tests
      #   working-directory: ./frontend
      #   run: npm test -- --watchAll=false

      # 5. Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 6. Set up Python for backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Fixed from 3.1 to 3.10

      # 7. Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 8. Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: pytest

      # 9. Deploy to Render using Deploy Hook
      - name: Deploy to Render
        if: success()
        run: curl -X POST $RENDER_DEPLOY_HOOK
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}